### ISSUE TITLE
Error: null value in column "id" of relation "sessions" violates not-null constraint

### ISSUE THREAD

**Issue by imsanchez** [express-rate-limit/rate-limit-postgresql#15]
### Description

Hey team, I'm working with a version of this repository that's causing an SQL issue:
```
error: null value in column "id" of relation "sessions" violates not-null constraint
    at /var/task/node_modules/.pnpm/pg-pool@3.6.1_pg@8.11.3/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  length: 327,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (null, aggregated_store, aggregated, 2023-11-08 14:49:03.357742+00, 2023-11-08 15:04:03.324+00).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL function "session_reset" statement 2',
  schema: 'rate_limit',
  table: 'sessions',
  column: 'id',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1968',
  routine: 'ExecConstraints'
}
{"error":{"code":"23502","column":"id","detail":"Failing row contains (null, aggregated_store, aggregated, 2023-11-08 14:49:03.357742+00, 2023-11-08 15:04:03.324+00).","file":"execMain.c","length":327,"line":"1968","name":"error","routine":"ExecConstraints","schema":"rate_limit","severity":"ERROR","table":"sessions","where":"SQL function \"session_reset\" statement 2"},"level":"error","message":"null value in column \"id\" of relation \"sessions\" violates not-null constraint","service":"backend","timestamp":"2023-11-08T14:49:03.433Z"}
```

Looking forward to any support and I appreciate the help. 🙏🏽 

### Library version

1.3.2

### Node version

18

### Module system

ESM

**Comment by nfriedly** [comment]
That ID is supposed to be auto-generated. It looks like [`uuid_generate_v1()` is supported from PostgreSQL 11 and newer](https://www.postgresql.org/docs/current/uuid-ossp.html); do you know what version of postgre you're on?

**Comment by imsanchez** [comment]
I read the migration and saw it's a UUID. I'm not sure why it's null. It happens pretty randomly and it's difficult to recreate.

I'm using [Vercel's Postgres storage](https://vercel.com/docs/storage/vercel-postgres), which appears to be version 15. 

In the meantime, I'm dropping the functions, tables, and schema from `rate_limit`, then reapplying the migrations.

**Comment by nfriedly** [comment]
Hum... I'm not sure how that's happening then. 

@adrianprelipcean do you have any ideas?

**Comment by adrianprelipcean** [comment]
@nfriedly can't think of any case where this is happen. Don't think there's any edge case when `uuid_generate_v1()` can return a null value.

**Comment by imsanchez** [comment]
Maybe something is wrong on my end with my setup. 

I needed `?sslmode=require` added to the `connectionString` but couldn't because of the way `dbConfig` is structured:
```
  const dbConfig = {
    database: config["database"] || "postgres",
    user: config["user"] || "postgres",
    password: config["password"] || "postgres",
    host: config["host"] || "localhost",
    port: config["port"] || 5432
  };
  await postgresMigrations.migrate(dbConfig, __dirname + "/migrations");
```

~~But I also investigated a bit into `uuid_generate_v1()` and the migrations don't have:~~
~~CREATE EXTENSION IF NOT EXISTS "uuid-ossp";~~
~~According to https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-uuid/ , is this needed to use uuid_generate_v1()?~~

Sorry, it is there!

**Comment by nfriedly** [comment]
It looks like you could set the `PGSSLMODE=require` in an environment property to solve that. 

But we can make it better by creating the `pg.Client first`, and then passing that in to postgres-migrations instead of building our own db config. (I should probably also make express-rate-limit allow `store.init()` to be asynchronous, though...)

**Comment by imsanchez** [comment]
> It looks like you could set the PGSSLMODE=require in an environment property to solve that.

Thank you! Will do this instead. 

I haven't experienced the issue since. I'm curious if maybe there is a conflict between when I run our Prisma migrations and the migrations from rate limit postgres.

**Comment by adrianprelipcean** [comment]
Marking this issue as resolved (`1.4.0` could potentially fix it)

**Comment by bvanderdrift** [comment]
Still running into this

```
postgres --version   
postgres (PostgreSQL) 16.1
```

```
"@acpr/rate-limit-postgresql": "^1.4.1",
```

```
error: null value in column "id" of relation "sessions" violates not-null constraint
```

**Comment by bvanderdrift** [comment]
I ended up manually deleting the `rate_limit` schema and `migrations` table and when the migration re-ran it worked.
