### ISSUE TITLE
Use `prefix` instead of `name`

### ISSUE THREAD

**Issue by gamemaker1** [express-rate-limit/rate-limit-postgresql#3]
> name - The unique name of the session. This is useful when applying multiple rate limiters with multiple stores.

The [`prefix`](https://github.com/express-rate-limit/express-rate-limit/pull/394) property was added as an optional property in the `Store` interface in v6.11.1 for the same purpose, and is taken into account by the [`singleCount`](https://github.com/express-rate-limit/express-rate-limit/blob/main/source/validations.ts#L154) validator.

Renaming `name` to `prefix` (just the store interface property, no need to change the sql schemas/queries) will help avoid issues like [#393](https://github.com/express-rate-limit/express-rate-limit/discussions/393).

---

Thanks,
Vedant

**Comment by adrianprelipcean** [comment]
Hi, would https://github.com/adrianprelipcean/express-rate-limit-postgresql/commit/ce3bde2989b9b65f44b68525308f91c8b68174df be sufficient?

**Comment by gamemaker1** [comment]
Definitely, it's great!
